
name: aozora-novel
dependencies:
- base
- text
- bytestring
- text-icu
- time
- directory
- pandoc
- sqlite-simple
- mtl
- free
- extensible
- microlens
- network-uri
- HTTP
- http-conduit
- hxt
- hxt-css
- hspec

library:
  source-dirs: src

executables:
  aozora-novel-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:  
    - aozora-novel

tests:
  aozora-novel-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aozora-novel

